os: linux
dist: xenial

language: cpp

compiler: g++

# script: cd tests/ && make 

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile
  - cd tests/ && make

deploy:
  provider: pages
  cleanup: false
  local_dir: docs
  token: $GH_REPO_TOKEN
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
